name: CI

on: ['push']

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: php-actions/composer@v5
    - uses: NWBY/pest-action@v1.2.0

    # `--do-not-cache-result` is to avoid: file_put_contents(/home/runner/work/phpfisx/phpfisx/.phpunit.result.cache): Failed to open stream: Permission denied 8 Error: Process completed with exit code 2.
    - run: ./vendor/bin/pest --do-not-cache-result